import { StyleSheet } from 'react-native';

export default StyleSheet.create(
    {
    row:{
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: 'blue',
        // paddingTop: 10,
        minHeight: '10%',
        minHeight: '20%',
        minWidth: '95%',
        padding: 5,

        flex: 10,
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    form:{
        borderWidth: 1,
        borderColor: 'red',
        backgroundColor: 'white',
        width: '90%',
        justifyContent: 'space-between',
        paddingBottom: 10,
        alignContent: 'center',
    },
    center_form_row:{
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: 'red',
        minHeight: 50,
        maxHeight: 70,
        minWidth: '95%',
        margin:10,
        flex: 0,
        flexDirection: 'row',
        justifyContent: "space-evenly",
        alignItems: 'center',
    },
    left_form_row:{
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: 'red',
        minHeight: 50,
        // maxHeight: 70,
        minWidth: '95%',
        margin:10,
        flex: 0,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    but_row:{
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: 'red',
        minHeight: 70,
        minWidth: '95%',
        padding: 10,
        flex: 1,
        flexDirection: 'row',
        justifyContent: "space-evenly",
        alignItems: 'center',
    },
    box:{
        backgroundColor: 'yellow',
        borderWidth: 1,
        borderColor: 'blue',
        minHeight: '90%',
        maxWidth: '20%',
        flex:1,
        alignItems:'center',
        paddingBottom: '1%',
        paddingTop: '1%',
    },
    box_btn_txt:{
        fontSize:30,
        padding:0,
        margin:0,
    },
    box_vlu_txt:{
        fontSize:20,
        padding:0,
        margin:0,
    },
    foot_btn:{
        borderWidth: 1,
        borderColor: 'blue',
        width: '40%',
        minHeight: '100%',
        alignItems: 'center',
        justifyContent: "center",
    },
    form_btn:{
        borderWidth: 1,
        borderColor: 'blue',
        minWidth: '80%',
        maxWidth: '80%',
        minHeight: 60,
        margin: 5,
        flex: 0,
        alignItems: 'center',
        justifyContent: "center",
    },
    updown_btn:{
        minWidth: '90%',
        minHeight: '30%',
        borderWidth: 1,
        borderColor: 'black',
        alignItems: 'center',
        justifyContent: 'center',
        color: "#FF3D00",
    },
    hor_updown_btn:{
        minWidth: '10%',
        minHeight: '60%',
        borderWidth: 1,
        borderColor: 'black',
        alignItems: 'center',
        justifyContent: 'center',
        color: "#FF3D00",
        margin: 0,
    },
    header:{
        borderWidth: 1,
        borderBottomWidth:2,
        borderColor: 'blue',
        fontSize:30,
        color: 'black',
        textAlign: 'center',
        textAlignVertical: 'center',
        padding: 0
    },
    subheader:{
        fontSize:20,
        color: 'black',
        textAlign: 'center',
        textAlignVertical: 'center',
        flex: 1,
    },
    label:{
        fontSize: 20,
        flex: 0,
        minWidth: '40%',
        // maxWidth: '45%',
    },
    input:{
        fontSize: 20,
        flex: 0,
        minWidth: '40%',
        maxWidth: '45%',
        borderWidth: 2,
        borderColor: 'grey',
        textAlign: 'center',
    },
    input_ML:{
        fontSize: 20,
        flex: 0,
        minWidth: '80%',
        maxWidth: '80%',
        borderWidth: 2,
        borderColor: 'grey',
        textAlign: 'left',
        textAlignVertical: 'top',
    },
    text:{
        fontSize: 20,
    },
    }
);