import { StyleSheet } from 'react-native';

export default StyleSheet.create(
    {
    container: {
        flex: 1,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'space-between',
        alignContent: 'center',
    },
    form:{
        borderWidth: 1,
        borderColor: 'red',
        backgroundColor: 'white',
        width: '90%',
        justifyContent: 'space-between', 
        alignContent: 'center',
    },
    form_row:{
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: 'red',
        minHeight: 50,
        minWidth: '95%',
        margin:10,
        flex: 0,
        
        flexDirection: 'row',
        justifyContent: "space-evenly",
        alignItems: 'center',
    },
    but_row:{
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: 'red',
        minHeight: '10%',
        minWidth: '95%',
        padding: 10,
        flex: 1,
        flexDirection: 'row',
        justifyContent: "space-evenly",
        alignItems: 'center',
    },
    foot_btn:{
        borderWidth: 1,
        borderColor: 'blue',
        width: '40%',
        minHeight: '100%',

        alignItems: 'center',
        justifyContent: "center",
    },
    form_btn:{
        borderWidth: 1,
        borderColor: 'blue',
        minWidth: '40%',
        maxWidth: '60%',
        minHeight: 60,
        margin: 5,
        flex: 0,
        alignItems: 'center',
        justifyContent: "center",
    },
    header:{
        borderWidth: 1,
        borderColor: 'blue',
        fontSize:30,
        color: 'black',
        textAlign: 'center',
        textAlignVertical: 'center',
        
        padding: '2%',
    },
    subheader:{
        fontSize:20,
        color: 'black',
        textAlign: 'center',
        textAlignVertical: 'center',
        flex: 1,
    },
    label:{
        fontSize: 20,
        flex: 0,
        minWidth: '40%',
        maxWidth: '45%',
    },
    input:{
        fontSize: 20,
        flex: 0,
        minWidth: '40%',
        maxWidth: '45%',
        borderWidth: 2,
        borderColor: 'grey',
        textAlign: 'center',
    },
    input_ML:{
        fontSize: 20,
        flex: 0,
        minWidth: '80%',
        maxWidth: '80%',
        borderWidth: 2,
        borderColor: 'grey',
        textAlign: 'left',
        textAlignVertical: 'top',
    },
    text:{
        fontSize: 20,
    },
    }
);